# NumPy

NumPy es una biblioteca fundamental para la computación científica en Python. Proporciona soporte para arreglos y matrices multidimensionales, junto con una amplia colección de funciones matemáticas para operar con estos datos de manera eficiente.

Además, NumPy es compatible con otras bibliotecas populares de Python, como SciPy y Matplotlib, lo que lo convierte en una herramienta versátil para el análisis y la visualización de datos.

Recuerda que, como todo módulo, para poder usarlo hay que instalarlo, importarlo y luego llamar a sus métodos o atributos a través del operador `.`.

Puedes instalar NumPy utilizando pip si aún no lo tienes instalado:

```bash
pip install numpy
```



```{admonition} Nota
:class: note

Ten en cuenta que la forma tradicional de importar numpy es renombrarlo como `np`. Esta nomenclatura es una convención en la comunidad de Python. Además, ahorra tecleo y hace tu código un poco más compacto.
```

In [19]:
import numpy as np

NumPy provee una clase de arrays multidimensionales (la clase `ndarray`), además de un _gran_ número de funciones que operan sobre arrays.

Los arrays de NumPy tienen una serie de características:
* permiten escribir código rápido (optimizado) que trabaja sobre arrays de datos. 
* todos los elementos son del mismo tipo de dato (p.ej. float)
* las operaciones aritméticas funcionan como en Matlab — esto significa que puedes evitar escribir bucles en Python (que tienden a ser lentos). En su lugar el 'bucle' se realiza en el código compilado subyacente.

## Creación de arrays y propiedades

Hay muchas formas de crear arrays. En esta sección veremos algunas de ellas.

La forma más clásica de crear un array de numpy es a partir de una lista o una tupla de Python, utilizando la función `numpy.array()`. Por ejemplo:


In [20]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


```{admonition} Tip
:class: tip
Todos los datos que contiene un array deben ser del mismo tipo. Si son distintos, numpy convierte todos al tipo de dato __más grande__. Podemos cambiar el tipo de dato utilizando el método `astype()`.
```

In [21]:
b = np.array((1.0, 2, 3+1j))
print(b.dtype)

complex128




Se puede crear un array usando `arange(ini,fin,incr)`, de forma similar a cómo crearíamos un `range` pero teniendo en cuenta que se puede usar también con valores reales. Posteriormente, cambiamos su forma a 3 filas y 5 columnas. 

In [22]:
a = np.arange(15) ## crea un array con valores del 0 al 14
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Un array de NumPy tiene mucha meta-información asociada que describe su forma, tipo de dato, etc. Aquí os dejamos algunos:

In [23]:
print(a.ndim) # número de dimensiones
print(a.shape) # forma del array
print(a.size) # número total de elementos
print(a.dtype) # tipo de dato
print(a.itemsize) # tamaño en bytes de cada elemento
print(type(a)) # tipo de objeto

1
(15,)
15
int64
8
<class 'numpy.ndarray'>


`linspace(ini,fin,n)` crea un array desde `ini` hasta `fin` (incluido) con `n` números equiespaciados. El argumento opcional `endpoint` especifica si el extremo superior está incluido en el array o no.

In [24]:
d = np.linspace(0, 1, 10)
print(d)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]



Análogo a `linspace()`, existe `logspace()` que crea un array con elementos equiespaciados en logaritmo. 


In [25]:
e=np.logspace(1, 3, num=10) # crea un array con 10 elementos desde 10^1 hasta 10^3
print(e)

[  10.           16.68100537   27.82559402   46.41588834   77.42636827
  129.1549665   215.443469    359.38136638  599.48425032 1000.        ]


### Arrays multidimensionales

Los arrays multidimensionales se almacenan en un espacio contiguo en memoria — esto significa que las columnas/filas necesitan desenrollarse (aplanarse) para que puedan pensarse como un único array unidimensional. 

Podemos crear arrays multidimensionales utilizando `reshape()`:

In [26]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podemos crear arrays multidimensionales directamente especificando la lista de valores con arrays anidados:



In [27]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


También podemos crear un array multidimensional de tamaño especificado inicializado a 0 fácilmente, usando la función `zeros()`.

In [28]:
b = np.zeros((10,8))
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

También existe `ones()` y `empty()`. Si queremos, podemos fijar explícitamente el tipo de dato del array usando la opción `dtype`. Por ejemplo, para crear un array de reales:

In [29]:
c = np.eye(10, dtype=np.float64)
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Existen muchas otras maneras de crear arrays unidimensionales o multidimensionales (full, identity, random, fromfile, fromfunction, etc.). Puedes consultar la [documentación oficial](https://numpy.org/doc/stable/user/basics.creation.html) para más detalles.

## Acceso a los elementos de un array

El acceso a elementos funciona de manera muy similar a como lo vimos con las listas. Recuerda, los índices en Python empiezan en 0.

Considera el siguiente array:

In [30]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Ahora mira el acceso a un solo elemento vs. un rango (usando lo que denominamos `slicing`). Cuando hacemos un rango, como `a[2:5]`, obtenemos los elementos empezando en el índice 2 y hasta, pero sin incluir, el índice 5.

Es decir, el slicing usa el intervalo: [inicio, fin), igual que con las secuencias en Python (listas, tuplas, cadenas).

In [31]:
a[2]

np.int64(2)

In [32]:
a[2:5]

array([2, 3, 4])

In [33]:
a[2:4]

array([2, 3])

Igual que pasaba en Matlab, el `:` puede usarse para especificar todos los elementos en esa dimensión

In [34]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Acceso a arrays multidimensionales

El acceso a los elementos de un array multidimensional se realiza utilizando múltiples índices separados por comas.


In [36]:
a=np.arange(25).reshape(5,5)
a[1,1]

np.int64(6)

Podemos acceder a filas o columnas separadas, poniendo una tupla:

In [38]:
a[0:2,(0,3)]

array([[0, 3],
       [5, 8]])

Para acceder a una columna específica, puedes usar el siguiente formato:

In [39]:
a[:,1]

array([ 1,  6, 11, 16, 21])

A veces queremos una vista unidimensional del array:

In [40]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

También podemos iterar — esto se hace sobre el primer eje (filas)

In [41]:
for row in a:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


o elemento por elemento

In [42]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


En general, queremos evitar iterar sobre los elementos de un array en Python — esto es lento. En su lugar queremos escribir y usar funciones que operen sobre el array entero a la vez.

## Modificación de los elementos de un array

Podemos añadir elementos a un array existente utilizando las funciones `numpy.append()` y `numpy.insert()`. Estas funciones permiten agregar elementos al final del array o en posiciones específicas, respectivamente, igual que hacíamos en listas. 

De la misma manera, podemos modificar elementos específicos de un array utilizando indexación y asignación directa. 
Además, podemos eliminar elementos de un array utilizando la función `numpy.delete()`, que permite eliminar elementos en posiciones específicas o según una condición dada.

```{admonition} Tip
:class: tip
Los arrays de NumPy son de tamaño fijo. Por lo tanto, cuando utilizas funciones como `append()` o `insert()`, en realidad estás creando un nuevo array con los elementos añadidos, ya que los arrays no pueden cambiar de tamaño dinámicamente como las listas de Python.
```



In [ ]:
a=np.arange(15) ## crea un array con valores del 0 al 14
a=np.append(a,20) ## añade el valor 20 al final del array
a=np.insert(a,5,99) ## inserta el valor 99 en la posición 5
a[3]=55 ## modifica el valor en la posición 4
a=np.delete(a,0) ## elimina el primer elemento
print(a)

[ 1  2 55  4 99  5  6  7  8  9 10 11 12 13 14 20]


## Operaciones con Arrays

La mayoría de las operaciones (`+`, `-`, `*`, `/`) funcionan sobre un array entero a la vez, elemento por elemento.

Ten en cuenta que el operador `*` no es una multiplicación matricial; `@` realiza la multiplicación matricial.

Vamos a crear un array sencillo para empezar

In [ ]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Multiplicar por un escalar multiplica cada elemento

In [ ]:
a*2

Sumar dos arrays suma elemento a elemento

In [ ]:
a + a

Multiplicar dos arrays multiplica elemento a elemento

In [ ]:
a*a

Dividir dos arrays (elemento a elemento)

In [ ]:
a/a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Podemos pensar en nuestro array 2-d como una matriz 3 x 4 (3 filas, 4 columnas). Podemos tomar la transpuesta para obtener una matriz 4 x 3, y luego hacer una multiplicación matricial

In [ ]:
b = a.transpose()
b = a.T # Otra opción para transponer
b

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
a @ b

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

Podemos sumar los elementos de un array:

In [ ]:
a.sum()

También podemos obtener fácilmente los extremos

In [ ]:
print(a.min(), a.max())

## Funciones universales

Numpy contiene algunas funcion matemáticas muy utilizadas, las hemos llamado funciones universales. Las funciones universales trabajan elemento a elemento. Algunos ejemplos: 

In [ ]:
b = a*np.pi/12.0
print(b)

In [ ]:
c = np.cos(b)
print(c)

In [ ]:
d = b + c 

In [ ]:
print(d)

````{admonition} Tip
:class: tip

A menudo querrás escribir tu propia función que opere sobre un array y devuelva un nuevo array. Podemos hacer esto igual que antes: la clave es usar las funciones del módulo `np` para cualquier operación, ya que ellas trabajan sobre, y devuelven, arrays.

````

# Operaciones avanzadas con NumPy

## Copiar arrays


Usar simplemente `=` no hace una copia de los valores y crea una nueva variable; al igual que con los objetos mutables, simplemente tendrás múltiples nombres apuntando al mismo objeto `ndarray` en memoria.

Por lo tanto, necesitamos entender si dos arrays, `A` y `B`, apuntan a:
* el mismo array, incluyendo forma y datos/espacio en memoria
* el mismo espacio de datos/memoria, pero quizás con formas diferentes (una _vista_)
* una copia separada de los datos (i.e. almacenada completamente de forma independiente en memoria)

Todas estas opciones son posibles.


Todas estas son posibles:

* `B = A`
  
  esto es _asignación_. No se hace copia. `A` y `B` apuntan a los mismos datos en memoria y comparten la misma forma, etc. Son solo dos etiquetas diferentes para el mismo objeto en memoria
  

* `B = A[:]`

  esto es una _vista_ o _copia superficial_. La información de la forma para A y B se almacena independientemente, pero ambos apuntan a la misma ubicación de memoria para los datos
  
  
* `B = A.copy()`

  esto es una copia _profunda_. Se creará un objeto completamente separado en memoria, con una ubicación en memoria completamente independiente.
  
Veamos ejemplos

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Aquí está la asignación — podemos usar el operador `is` para probar la identidad

In [ ]:
b = a
b is a

True

Como `b` y `a` son el mismo objeto, los cambios en la forma de uno se reflejan en el otro — no se hizo copia:

In [ ]:
b.shape = (2, 5)
print(b)
a.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

Una copia superficial crea una nueva *vista* en el array — los _datos_ son los mismos, pero las propiedades del array pueden ser diferentes

In [ ]:
a = np.arange(12)
c = a[:]
a.shape = (3,4)

print(a)
print(c)
c is a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


False

Dado que los datos subyacentes son la misma memoria, cambiar un elemento de uno se refleja en el otro

In [ ]:
c[1] = -1
a

array([[ 0, -1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Hay muchas maneras de indagar si dos arrays son el mismo, vistas, si poseen sus propios datos, etc.

In [ ]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


Para hacer una copia de los datos de un array que puedas tratar independientemente del original, necesitas una copia _profunda_. En este caso, ya no hay relación entre los dos arrays, y los cambios en uno no modificarán el otro:

In [ ]:
d = a.copy()
d[:,:] = 0.0

print(a)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Comparaciones en arrays

En general, podemos comparar arrays en numpy, y  nos devolverá el resultado elemento a elemento:

In [ ]:
np.array([4, 7, 1])==np.array([3, 7 , 1])

array([False,  True,  True])

Si queremos conocer si todos los elementos cumplen alguna comparación, podemos usar los métodos `all()` o `any()`:

In [ ]:
print((np.array([4, 7, 1]) > 2).all())
print((np.array([4, 7, 1]).any() > 6).any())

False
False


Por último, podemos utilizar el método where para crear un array basado en una condición:


In [ ]:
a = np.array([4, 7, 1])
b = np.where(a > 5, a, 0)   
# b es ahora array([0, 7, 0])

## Indexado booleano

Hay muchas formas de indexar arrays para acceder solo a aquellos elementos que cumplen cierta condición

In [ ]:
a = np.arange(12).reshape(3,4)
a

Aquí ponemos a cero todos los elementos del array que son > 4

In [ ]:
a[a > 4] = 0
a

y ahora, todos los ceros a -1

In [ ]:
a[a == 0] = -1
a

In [ ]:
a == -1

Si tenemos 2 pruebas, necesitamos usar `logical_and()` o `logical_or()`. Si usamos los operadores `and` o `or`, obtendremos un error porque Python no sabe cómo manejarlos con arrays de numpy.

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
a[np.logical_or(a == 0, np.logical_and(a > 3, a <= 9))] = 100.0
a

array([[100,   1,   2,   3],
       [100, 100, 100, 100],
       [100, 100,  10,  11]])